### PR TITLE
fix: check Primitive in DeepPartial (#19)

### LINKED ISSUE #19: DeepPartial does not work with index signatures
The following errors:

```ts
import { DeepPartial } from 'ts-essentials';

interface Params {
  [key: string]: any
}

interface Route {
  params: Params
}

const route: DeepPartial<Route> = {
  params: {
    test: '123'
  }
}
```

```
Type 'string' is not assignable to type 'DeepPartial<{}>[] | ReadonlyArray<DeepPartial<{}>> | DeepPartial<any>'.
```

https://stackblitz.com/edit/typescript-eu3ajv

### PR DESCRIPTION
**Pull request by lucifer1004**
This PR should fix #19

### CODE REVIEW

**Comment by krzkaczor** [comment]
Could you write some tests? I think there are already some cases for DeepPartial. Thanks!

File: test/index.ts [hunk 1]
```diff
@@ -15,6 +16,30 @@ import {
...
+    nested: {
+      date: Date;
+    };
+    params: Params;
+  };
+
+  type Expected = {
+    simple?: number;
+    nested?: {
+      date?: DeepPartial<Date>;
```
Comment (krzkaczor) [inline test/index.ts]: Do not use `DeepPartial` in expected type since its still not clear what should be the result.
Probably the type should look like this:

```typescript
type Expected = {
    simple?: number;
    nested?: {
      date?: Date;
    };
    params?: {
      [key: string]?: any;
    };
  };
```

Comment (lucifer1004) [reply test/index.ts]: `[key: string]?: any` is not valid, and I have not come up with a solution.

Comment (lucifer1004) [reply test/index.ts]: Since `[key: string]` is already a partial property, I think we can directly use `[key: string]: any`

**Comment by krzkaczor** [comment]
Solves https://github.com/krzkaczor/ts-essentials/issues/37 as well.

**Comment by krzkaczor** [comment]
@lucifer1004 Great PR, thanks! Merging it now.

**Comment by krzkaczor** [comment]
Published as `ts-essentials@2.0.11`
